version: '3.8'

services:
  # Service MySQL
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: FORTINATE-my-secret@9630
      MYSQL_DATABASE: daily_app
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Service Backend
  daily-meeting-backend:
    image: marouanelk02/daily-app-backend:latest
    container_name: dailyMeeting-backend-container
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/daily_app?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: FORTINATE-my-secret@9630
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_SHOW_SQL: "false"
      JWT_SECRET: cYAr0yTHvx4NWxZzBFIzndSShkh6JLUX9ZbJa4cImdsO1VADkCJzg2nXKLgywN7E
      JWT_EXPIRATIONS: "3600000"
      UPLOAD_PATH: /app/src/main/resources/images
      LOGO_PATH: /app/src/main/resources/static/hps.png
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: "587"
      SPRING_MAIL_USERNAME: marouanelk02@gmail.com
      SPRING_MAIL_PASSWORD: ipzprwexdihebsxd
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
    volumes:
      - backend-images:/app/src/main/resources/images

  # Service Frontend
  daily-meeting-frontend:
    image: marouanelk02/daily-app-frontend:latest
    container_name: dailyMeeting-frontend-container
    ports:
      - "80:80"
    depends_on:
      - daily-meeting-backend

volumes:
  mysql-data:
    driver: azure_file
    driver_opts:
      share_name: mysql-data
      storage_account_name: azurefilesharedailyapp
      storage_account_key: MajltCJxudlgBrwkc9L7fq8B/Mn/K7LbtKM+IqQrMAfFTju5dfNrLFiWTLk9WjZ/H76NEVxMGfSK+ASt7LIOAA==
  backend-images:
    driver: azure_file
    driver_opts:
      share_name: backend-images
      storage_account_name: azurefilesharedailyapp
      storage_account_key: MajltCJxudlgBrwkc9L7fq8B/Mn/K7LbtKM+IqQrMAfFTju5dfNrLFiWTLk9WjZ/H76NEVxMGfSK+ASt7LIOAA==